image: docker:latest

services:
- docker:dind

build:
  script:
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN registry.gitlab.com
    - docker build -t registry.gitlab.com/dfederschmidt/docker-pipenv-sample .
    - docker push registry.gitlab.com/dfederschmidt/docker-pipenv-sample